[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_VERSION = "10"
  NETLIFY = "true"
  # Increase memory for build process
  NODE_OPTIONS = "--max_old_space_size=4096"
  # Build timeout (10 minutes)
  BUILD_TIMEOUT = "600"
  # Disable secrets scanning - we handle secrets properly through environment variables
  # The scanner is giving false positives on environment variable names and dashboard URLs
  SECRETS_SCAN_ENABLED = "false"
  # Enable Next.js build cache
  NETLIFY_USE_YARN = "false"
  # Skip TypeScript checks for test files
  SKIP_TESTS = "true"
  
# Prevent Netlify from timing out during build
[build.processing]
  skip_processing = false

[dev]
  command = "npm run dev"
  port = 3000

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # Clickjacking protection
    X-Frame-Options = "DENY"
    # Strict transport security (HTTPS only)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Permissions policy
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(self), usb=(), vr=(), accelerometer=(), gyroscope=(), magnetometer=()"
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://challenges.cloudflare.com https://*.clerk.accounts.dev https://*.clerk.dev https://va.vercel-scripts.com https://vitals.vercel-insights.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://*.convex.cloud https://*.clerk.accounts.dev https://*.clerk.dev https://api.stripe.com https://api.openai.com https://generativelanguage.googleapis.com wss://*.convex.cloud https://vitals.vercel-insights.com;
      frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://challenges.cloudflare.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """

# API security headers
[[headers]]
  for = "/api/*"
  [headers.values]
    # Additional API-specific headers
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    # Rate limiting info (will be set by rate limiter)
    X-RateLimit-Limit = "100"
    X-RateLimit-Window = "900"

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Webhook endpoints - disable caching
[[headers]]
  for = "/api/*-webhook"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Health check endpoint
[[headers]]
  for = "/api/health"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects for clean URLs and SPA routing
[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/student-intake/*"
  to = "/student-intake/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/preceptor-intake/*"
  to = "/preceptor-intake/:splat"
  status = 200
  force = false

# API route handling
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = false

# Clerk authentication routes
[[redirects]]
  from = "/sign-in"
  to = "/sign-in"
  status = 200

[[redirects]]
  from = "/sign-up"
  to = "/sign-up"
  status = 200

# Force HTTPS redirect
[[redirects]]
  from = "http://sandboxmentoloop.online/*"
  to = "https://sandboxmentoloop.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.sandboxmentoloop.online/*"
  to = "https://sandboxmentoloop.online/:splat"
  status = 301
  force = true

# WWW to non-WWW redirect
[[redirects]]
  from = "https://www.sandboxmentoloop.online/*"
  to = "https://sandboxmentoloop.online/:splat"
  status = 301
  force = true

# Legacy route redirects (if any)
[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301

# 404 fallback for SPA
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404