[build]
  command = "npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NETLIFY = "true"
  
# Prevent Netlify from timing out during build
[build.processing]
  skip_processing = false

[dev]
  command = "npm run dev"
  port = 3000